# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "393684f43f125d20395a1b601fdcc369"
name = "beta-test"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscription_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_themes,write_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
